<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intro2P</name>
   <tag></tag>
   <elementGuidId>99ea017b-8d1d-4bb9-aa38-e435f08ed616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home-classroom-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-classroom-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0bf59ff9-07d3-4c4d-8d52-61b3370ea529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1</value>
      <webElementGuid>be9a6760-4c3c-4cc2-b615-b35deaa3395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-classroom-name</value>
      <webElementGuid>c967265e-e9ff-4088-8835-7a79a4f1c8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intro2P</value>
      <webElementGuid>4f697522-a318-487d-bee3-43d3b22f6624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;card&quot;]/div[@class=&quot;card&quot;]/a[@id=&quot;home-classroom-name&quot;]</value>
      <webElementGuid>8f5019af-1bea-484b-bad6-a1dbf304db46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='home-classroom-name']</value>
      <webElementGuid>dc0614c3-4dad-414b-ac76-8bfe05a1ddde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card']/div/a</value>
      <webElementGuid>a7410646-6ad7-4975-a5fe-a4d9d774566f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intro2P')]</value>
      <webElementGuid>1c131c89-d096-4021-9fea-f9f975aa3475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinh Tu Kien'])[1]/following::a[1]</value>
      <webElementGuid>8153ae22-6939-466f-ae6a-95d69c2fd65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::a[1]</value>
      <webElementGuid>3f3ce99d-89be-4bb7-b6d5-8ea73c1b633f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction to Programming'])[1]/preceding::a[1]</value>
      <webElementGuid>94a199b1-5a92-470d-b0e0-90be8ab3b9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intro2IT'])[1]/preceding::a[1]</value>
      <webElementGuid>e86dbcfa-7172-4eba-958b-d8d4886ab7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intro2P']/parent::*</value>
      <webElementGuid>0c312634-c970-4939-b248-14017d69715c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/1')]</value>
      <webElementGuid>2786ac55-3384-4bf0-a813-6baec8f0b95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>654e85d4-5a48-4121-be72-7ea74dd61cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/classes/1' and @id = 'home-classroom-name' and (text() = 'Intro2P' or . = 'Intro2P')]</value>
      <webElementGuid>9d09d454-f213-4bef-bce4-323badfa76e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
