<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grades</name>
   <tag></tag>
   <elementGuidId>fa97d786-f22d-4511-b326-5793ae5ae99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='classroom-grade-link'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.classroom-grade-btn.btn.btn-primary > #classroom-grade-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6bdc7e81-d22a-416b-8eb4-286b7b6af714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classroom-grade-link</value>
      <webElementGuid>de958cbf-86c3-4cdc-beb1-f23811079c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1/g</value>
      <webElementGuid>246d6c0b-6896-40af-acad-7b81c0619660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grades</value>
      <webElementGuid>c7795b8c-acd0-4a7d-9efc-da3b9abf333b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;classroom-grade-btns&quot;]/button[@class=&quot;classroom-grade-btn btn btn-primary&quot;]/a[@id=&quot;classroom-grade-link&quot;]</value>
      <webElementGuid>dd6184b2-1ece-4ff7-a870-d49dd3349526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='classroom-grade-link'])[2]</value>
      <webElementGuid>889576fd-ee4a-4aff-aff5-98cbc378c50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/button[2]/a</value>
      <webElementGuid>b0117314-2a7b-4125-bf28-6acda51722c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grades')]</value>
      <webElementGuid>54cb5297-35a6-413e-b02b-8f073004df87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade Structure'])[1]/following::a[1]</value>
      <webElementGuid>fd198cca-9944-4c0f-bb78-63daa71b4998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Invite User'])[1]/following::a[2]</value>
      <webElementGuid>cede8328-30af-4e0d-b155-825c3f941b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Van A (Owner)'])[1]/preceding::a[1]</value>
      <webElementGuid>fd70d76f-12ee-4d44-bd1c-eaf3e0eb5384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classroom Ad'])[1]/preceding::a[1]</value>
      <webElementGuid>7f7b395e-3a5e-44be-b250-cadc1bbff9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grades']/parent::*</value>
      <webElementGuid>1d58713c-bc13-4a92-a62a-fd29360b6cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/classes/1/g')])[2]</value>
      <webElementGuid>315b9848-b71f-4847-9fb7-eeb1e3629bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/a</value>
      <webElementGuid>e3c32eca-dc12-4ba9-9bb8-248e5e1b0659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'classroom-grade-link' and @href = '/classes/1/g' and (text() = 'Grades' or . = 'Grades')]</value>
      <webElementGuid>5a6a64f3-5b54-4a06-8e22-b73d6031f511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
