<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intro2P</name>
   <tag></tag>
   <elementGuidId>72ad6e8b-1db9-46b0-beec-bd02db4df539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home-classroom-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-classroom-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b34b2078-1cd5-4058-9a89-99011db7a752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1</value>
      <webElementGuid>b6cd4a19-2681-4181-89fb-32d051b831f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-classroom-name</value>
      <webElementGuid>5fba9e5c-310f-41d7-881d-474493589ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intro2P</value>
      <webElementGuid>e919f063-e0c5-47bf-b1a0-1fc807c34855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;card&quot;]/div[@class=&quot;card&quot;]/a[@id=&quot;home-classroom-name&quot;]</value>
      <webElementGuid>ed19359b-f892-4e5c-b011-60f9d31e1096</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='home-classroom-name']</value>
      <webElementGuid>ae852c34-093a-4c97-b48c-94e56cc04f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card']/div/a</value>
      <webElementGuid>6f0dfcaf-c9c7-498b-a587-cf77b6a12601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intro2P')]</value>
      <webElementGuid>8c548b5e-9653-4f3b-a640-e440e533ba52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Van A'])[1]/following::a[1]</value>
      <webElementGuid>d308fefd-1cef-42ca-a416-26e2d78731ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::a[1]</value>
      <webElementGuid>7505cf3e-66a2-41f0-a24e-47526e018df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction to Programming'])[1]/preceding::a[1]</value>
      <webElementGuid>2df1bdb6-0bab-4c75-8ca7-c2c944d070df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intro2IT'])[1]/preceding::a[1]</value>
      <webElementGuid>cfa499a1-110f-4ae5-af33-3050168a9787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intro2P']/parent::*</value>
      <webElementGuid>8601ae0b-4fc4-40f3-a58c-552218017df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/1')]</value>
      <webElementGuid>d5b9b89e-a4c8-4716-ab78-5de4ea9bf234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>b17ee91e-bf40-4511-a0c1-756082f163a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/classes/1' and @id = 'home-classroom-name' and (text() = 'Intro2P' or . = 'Intro2P')]</value>
      <webElementGuid>a64925d4-fa7e-4bb9-afd5-6958bc45c448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
