<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Invite User</name>
   <tag></tag>
   <elementGuidId>a125d15d-cb41-4528-bb62-d0bd6c84f440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='invite-user-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#invite-user-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c1ceb75-5d95-411b-90ca-808b10202de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>invite-user-btn</value>
      <webElementGuid>097373b2-2f93-49ee-83ac-cf5f42a69eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a11e1fef-a28d-4eb6-922c-ae6433b0a889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>4c8d966b-65e8-47ee-a5b9-f7c3dc80d874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Invite User</value>
      <webElementGuid>cd4e1cb6-275b-492b-9e8d-332f8983c32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;invite-user-btn&quot;)</value>
      <webElementGuid>b094df71-ede6-4f4b-9287-5ef22bea92bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='invite-user-btn']</value>
      <webElementGuid>0f72c85c-dee6-4669-8b1a-9cc1252050c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='invite-user-modal']/button</value>
      <webElementGuid>6d88d5f1-9f72-4618-b867-4bbac19acf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invitation Link'])[1]/following::button[1]</value>
      <webElementGuid>3172e137-223d-4969-a05b-df86a18a580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade Structure'])[1]/preceding::button[1]</value>
      <webElementGuid>4bfa15e1-17ad-4ea5-98b3-ac4f5a37c6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grades'])[1]/preceding::button[2]</value>
      <webElementGuid>a6580e47-f25a-41a0-b0f6-6135965e28d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Invite User']/parent::*</value>
      <webElementGuid>48dfc97c-05ab-439d-aef0-00fcb4e744ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>12a05069-19d0-4e86-8b9e-d6d07a037ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'invite-user-btn' and @type = 'button' and (text() = '+ Invite User' or . = '+ Invite User')]</value>
      <webElementGuid>46784430-1ad5-473d-ab1a-e9db1e743289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
