<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grade Structure</name>
   <tag></tag>
   <elementGuidId>37c05218-c3d2-435d-afae-0dcb98048069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='classroom-grade-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#classroom-grade-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7bdc78d7-b572-4d61-894e-902736adc94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classroom-grade-link</value>
      <webElementGuid>3b9fa6a4-f174-4482-bd6a-da1199c4c3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1/grade</value>
      <webElementGuid>770f436e-005e-4658-be3d-80fd964c837f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grade Structure</value>
      <webElementGuid>a67cf103-e345-49d6-8bf1-e0631bd99c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;classroom-grade-btns&quot;]/button[@class=&quot;classroom-grade-btn classroom-grade-structure-btn btn btn-success&quot;]/a[@id=&quot;classroom-grade-link&quot;]</value>
      <webElementGuid>bb7a4f38-dcad-490a-8359-32ae90315777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='classroom-grade-link']</value>
      <webElementGuid>e0b2c09a-8a1a-42c8-b6c5-e81f8b0d47b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/button/a</value>
      <webElementGuid>508503c2-538e-4e0f-bdcc-5d83f0f36374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grade Structure')]</value>
      <webElementGuid>461c09db-e8d1-4f94-a26d-d5497f541a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Invite User'])[1]/following::a[1]</value>
      <webElementGuid>ef9463cf-3454-4892-9787-8fc3f15706ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invitation Link'])[1]/following::a[1]</value>
      <webElementGuid>efd1c4e8-833c-40ee-bd71-733ec28aa3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grades'])[1]/preceding::a[1]</value>
      <webElementGuid>98064f6d-5ac9-4aa0-9a20-88127bc39d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Van A (Owner)'])[1]/preceding::a[2]</value>
      <webElementGuid>611db6f0-f9a2-43aa-89eb-bc9fbb7c51c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grade Structure']/parent::*</value>
      <webElementGuid>2a0d2354-dab9-420f-ba86-94da0079e20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/1/grade')]</value>
      <webElementGuid>f6581572-3866-4717-b7c1-cd9816ef5124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>91036332-37fc-45be-a6ce-f9983c5d25c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'classroom-grade-link' and @href = '/classes/1/grade' and (text() = 'Grade Structure' or . = 'Grade Structure')]</value>
      <webElementGuid>e9844d06-5a0a-4e31-b56f-25f51025515d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
