<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intro2IT</name>
   <tag></tag>
   <elementGuidId>eed99318-ad84-44e2-ab6d-eb68aefbf395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='home-classroom-name'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f0494aa-0f9c-44bf-8ce4-cf7067a52012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/2</value>
      <webElementGuid>3661ae51-0dc7-4cab-94a2-0631f2de8253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-classroom-name</value>
      <webElementGuid>badcddc3-0fe6-4966-80a2-6afcd9a9a524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intro2IT</value>
      <webElementGuid>c187c8e6-20f5-46e2-aa2c-f481411f619e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;card&quot;]/div[@class=&quot;card&quot;]/a[@id=&quot;home-classroom-name&quot;]</value>
      <webElementGuid>5a87136b-133e-4a9b-9b32-b09bea1f4d71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='home-classroom-name'])[2]</value>
      <webElementGuid>6a7a5591-7e45-41b4-a147-1ebef72d7afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='card']/div/a)[2]</value>
      <webElementGuid>e037686d-b26a-4c25-9197-1b737b5c7fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intro2IT')]</value>
      <webElementGuid>3ea1662e-0aa2-4e8a-8a2e-950cef8928cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction to Programming'])[1]/following::a[1]</value>
      <webElementGuid>5cf592ae-52fd-4f02-b2af-45560c45a033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intro2P'])[1]/following::a[1]</value>
      <webElementGuid>3eef72d8-3dc8-4cc9-b49d-fcf11625e255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction to Information Technology'])[1]/preceding::a[1]</value>
      <webElementGuid>89238d14-84a9-4b20-a835-aabcf5b0d777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intro2IT']/parent::*</value>
      <webElementGuid>776aa476-a743-451f-96e7-f444918ce249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/2')]</value>
      <webElementGuid>8f6e5c05-7bda-4230-809f-2d74e915f277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>9264121a-93cb-4ba0-b704-a211ca66938a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/classes/2' and @id = 'home-classroom-name' and (text() = 'Intro2IT' or . = 'Intro2IT')]</value>
      <webElementGuid>c8be38c3-1f36-4616-b594-d1629e9cb621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
