<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Exercise 3Points 3</name>
   <tag></tag>
   <elementGuidId>885f676e-fb19-492e-81de-ad4cc0729a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[4]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9043b01d-0128-4f78-bdaa-0014bc250308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAccordionSummary-content</value>
      <webElementGuid>245a2455-57c5-4b05-8b06-9296123a33bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exercise 3Points: 3</value>
      <webElementGuid>7e568810-85cb-49c6-9dc2-ee276018a1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;section&quot;]/div[4]/div[@class=&quot;assignment-item-viewonly&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiButtonBase-root MuiAccordionSummary-root&quot;]/div[@class=&quot;MuiAccordionSummary-content&quot;]</value>
      <webElementGuid>e0fde08a-8d10-4e28-8f39-f37439c6404a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>5ec503e4-2f54-4fc7-8c5a-2c3f8878b930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vinh Tu Kien'])[1]/following::div[36]</value>
      <webElementGuid>c0274bfd-a202-48e2-8cb8-40677e223a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::div[38]</value>
      <webElementGuid>17ee7d44-4789-4fa7-99b5-5a5268b49e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to class'])[1]/preceding::div[16]</value>
      <webElementGuid>d4ff54de-89f1-42ba-bd62-0d2eb6018a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>d75f0f92-43f3-42c1-9009-659c6e1de1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Exercise 3Points: 3' or . = 'Exercise 3Points: 3')]</value>
      <webElementGuid>c1da0f85-5093-47f7-9523-11fef701d2ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
