<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Grades</name>
   <tag></tag>
   <elementGuidId>4fb514bc-2f7e-470f-8372-569ec5829f9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='classroom-grade-link'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.classroom-grade-btn.btn.btn-primary > #classroom-grade-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>daa5bb6d-6f48-4295-8ec4-eb026e7e4a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>classroom-grade-link</value>
      <webElementGuid>3ac567f5-fcd7-499e-9f08-69f3812c8304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1/g</value>
      <webElementGuid>cbe82053-47d9-4f2f-9b7e-81d0dc1e4dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grades</value>
      <webElementGuid>d0dcf848-f1ba-4f05-b001-8f42169f527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;classroom-grade-btns&quot;]/button[@class=&quot;classroom-grade-btn btn btn-primary&quot;]/a[@id=&quot;classroom-grade-link&quot;]</value>
      <webElementGuid>d6790ae9-229f-41dc-834c-970758ccb632</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='classroom-grade-link'])[2]</value>
      <webElementGuid>c03e1097-ad4b-4814-9e8f-9314d4d8834d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/button[2]/a</value>
      <webElementGuid>eb5bd847-dbb2-4a05-8317-ac318b08cb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Grades')]</value>
      <webElementGuid>102103d6-85e0-4258-a18f-76be2505845e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade Structure'])[1]/following::a[1]</value>
      <webElementGuid>a8e7ed59-b9a2-464f-bc0f-93d55dd7f857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Invite User'])[1]/following::a[2]</value>
      <webElementGuid>b87efa6b-8fca-44d7-be9d-9f804986e5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Van A (Owner)'])[1]/preceding::a[1]</value>
      <webElementGuid>5f36d37c-9100-4ebe-b75c-d37a8af0fad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classroom Ad'])[1]/preceding::a[1]</value>
      <webElementGuid>65e3cf79-de17-4efe-b8b4-a00900dc2abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grades']/parent::*</value>
      <webElementGuid>9ef18d64-48eb-466d-a357-10055ad87ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/classes/1/g')])[2]</value>
      <webElementGuid>6a35ccde-57c1-41e7-9d99-35d43b812a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/a</value>
      <webElementGuid>650c637f-758d-463c-85e9-d2a4de402e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'classroom-grade-link' and @href = '/classes/1/g' and (text() = 'Grades' or . = 'Grades')]</value>
      <webElementGuid>7c433210-80db-49aa-8b21-0735cbc73880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
