<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Intro2P</name>
   <tag></tag>
   <elementGuidId>ac7a9c9f-130c-426f-945d-ce47f53cb5e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home-classroom-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#home-classroom-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36fe0d66-dd79-4b94-8457-38ad3b4c0a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1</value>
      <webElementGuid>898e9db9-0510-4935-ad65-c4b1ae56201b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home-classroom-name</value>
      <webElementGuid>41aadf6e-20c7-456f-ab88-cd1e9ce8100d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intro2P</value>
      <webElementGuid>6291296f-2492-4984-a6d6-17e8a1e93bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]/div[@id=&quot;card&quot;]/div[@class=&quot;card&quot;]/a[@id=&quot;home-classroom-name&quot;]</value>
      <webElementGuid>57aa0c39-7f4f-4a11-b876-2c81b5773127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='home-classroom-name']</value>
      <webElementGuid>a592879f-0b19-4699-8fb6-f940d923d706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='card']/div/a</value>
      <webElementGuid>1bf4a9e9-5e98-412e-92ac-38d2d61c8c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Intro2P')]</value>
      <webElementGuid>2129da48-6a88-49ba-a42a-049068cc2a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyen Van A'])[1]/following::a[1]</value>
      <webElementGuid>f646e4a3-12e5-4803-8127-53da6bbb621b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::a[1]</value>
      <webElementGuid>0f1c8a3a-fd17-43c9-9cad-a3bbd2b8deb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduction to Programming'])[1]/preceding::a[1]</value>
      <webElementGuid>8c206fb4-7e28-4148-ba29-5a7015796563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intro2IT'])[1]/preceding::a[1]</value>
      <webElementGuid>684897db-68a9-4dab-8003-5f9839b1b66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intro2P']/parent::*</value>
      <webElementGuid>07d253ce-697b-49b5-89e0-4fac2747aeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/1')]</value>
      <webElementGuid>2f6d8f39-a90b-426b-862b-649f6cb83504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>2ccb98e8-ac84-4a5b-ab17-21b693d23287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/classes/1' and @id = 'home-classroom-name' and (text() = 'Intro2P' or . = 'Intro2P')]</value>
      <webElementGuid>61b83764-5c37-488a-a691-08c25fa96e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
