<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Grades Review</name>
   <tag></tag>
   <elementGuidId>0bcf0fc5-4247-43f4-9ac8-a99328a77d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='g-m-btns']/button[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.g-view-grades-rv-btn.btn.btn-secondary > a.grades-back-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>faecb83d-20f7-460f-993f-3f03e43a75c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grades-back-btn</value>
      <webElementGuid>e510bcee-8368-462c-9d75-1a0f8fe9e97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/classes/1/g-rv</value>
      <webElementGuid>3067a6b1-4ea7-448f-bbe8-e1f0b3d41421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Grades Review</value>
      <webElementGuid>2c1b5cc4-1b32-4475-b8cc-ac3d64f96178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-m-btns&quot;)/button[@class=&quot;g-view-grades-rv-btn btn btn-secondary&quot;]/a[@class=&quot;grades-back-btn&quot;]</value>
      <webElementGuid>eda3d472-b5db-45c3-88db-0cd200b6c709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-m-btns']/button[3]/a</value>
      <webElementGuid>5374ddc3-007e-4655-a0af-1a2ea54e0768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Grades Review')]</value>
      <webElementGuid>a99ad4bc-c349-40ce-af09-6566024de1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Grades'])[1]/following::a[1]</value>
      <webElementGuid>d51eda8d-1451-4dc9-ba0f-5de41838bcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Grades template'])[1]/following::a[1]</value>
      <webElementGuid>f07f15ce-6bcd-43af-a977-27ac35e043c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Student List template'])[1]/preceding::a[1]</value>
      <webElementGuid>ac47db3c-c03e-4037-90ed-233e93361bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Student List'])[1]/preceding::a[1]</value>
      <webElementGuid>ebae4141-6177-42da-be25-4912313f8e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Grades Review']/parent::*</value>
      <webElementGuid>fbe4e509-ee8b-4965-9d05-0f97c9f634f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/classes/1/g-rv')]</value>
      <webElementGuid>c2c6a2f0-f363-4a6a-91eb-6ce4e5379eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/a</value>
      <webElementGuid>5e561086-1d7c-49a1-8115-cb8883fc1fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/classes/1/g-rv' and (text() = 'View Grades Review' or . = 'View Grades Review')]</value>
      <webElementGuid>897e826a-09ab-456e-8cc3-857465a7da7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
